### ISSUE TITLE
How to add the key with a "Dictionary" key type?

### ISSUE THREAD

**Issue by NISHMANGAL** [BIG-RAT/Managed-App-Schema-Builder#3]
How to add the key with a "Dictionary" key type?

**Comment by BIG-RAT** [comment]
Not (directly) possible.  Hacky work around would be to create a separate json file for the nested dictionary then copy the necessary contents into the parent json file.

**Comment by talkingmoose** [comment]
Agree with @BIG-RAT on this one. It's possible, but would likely require a lot of complex development work because dictionaries can be virtually limitless.

I have a sample Jamf manifest that will show you the structure for a dictionary. Have a look at the serverList property. You can copy that property, insert it into your manifest and change it to what you need.

[https://github.com/Jamf-Custom-Profile-Schemas/jamf-manifests/blob/master/Disk%20Manager%20(net.talkingmoose.diskmanager).json](https://github.com/Jamf-Custom-Profile-Schemas/jamf-manifests/blob/master/Disk%20Manager%20(net.talkingmoose.diskmanager).json)
